apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotadice-frontend
  labels:
    app: gotadice-frontend
    ci-hash: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotadice-frontend
  template:
    metadata:
      labels:
        app: gotadice-frontend
        ci-hash: latest
    spec:
      containers:
      - name: gotadice-frontend
        image: razorbreak/gotadice-frontend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gotadice-frontend
  labels:
    app: gotadice-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: gotadice-frontend