# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  backend-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-dependencies-{{ checksum "backend/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-pip-dependencies-
      - run:
          name: install dependencies
          command: |
            cd backend
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths: [backend/venv]
          key: v1-pip-dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          name: Run unit tests
          command: |
            cd backend
            . venv/bin/activate
            make test

  backend-lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-dependencies-{{ checksum "backend/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-pip-dependencies-
      - run:
          name: install dependencies
          command: |
            cd backend
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -O /bin/hadolint && chmod +x /bin/hadolint
      - save_cache:
          paths: [backend/venv]
          key: v1-pip-dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          working_directory: backend
          name: Run linters
          command: |
            cd backend
            . venv/bin/activate
            make lint

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  default: 
    jobs:
      - backend-test
      - backend-lint