# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  backend-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-dependencies-{{ checksum "backend/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-pip-dependencies-
      - run:
          working_directory: backend
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths: [backend/venv]
          key: v1-pip-dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          working_directory: backend
          name: Run unit tests
          command: |
            . venv/bin/activate
            make test

  backend-lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-dependencies-{{ checksum "backend/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-pip-dependencies-
      - run:
          working_directory: backend
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths: [backend/venv]
          key: v1-pip-dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          working_directory: backend
          name: Run linters
          command: |
            . venv/bin/activate
            make lint

  docker-build:
    docker:
      - image: docker:24.0.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          working_directory: backend
          name: build docker image
          command: |
            docker build -t $DOCKERHUB_ACCESS_ID/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_WORKFLOW_ID:0:7} .

  docker-scan:
    docker:
      - image: docker:dind
    steps:
      - run:
          name: install grype
          command: |
            curl -s https://api.github.com/repos/anchore/grype/releases/latest | grep \"https.*grype.*linux_amd64.tar.gz\" | cut -d : -f 2,3 | tr -d \\\" | wget -qi - && tar -xvzf grype*.tar.gz grype && ./grype version
      - run:
          name: scan docker vulnerabilities
          command: |
            ./grype -f high $DOCKERHUB_ACCESS_ID/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_WORKFLOW_ID:0:7}

  docker-push:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_ACCESS_ID
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run:
          working_directory: backend
          name: build docker image
          command: |
            docker push $DOCKERHUB_ACCESS_ID/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_WORKFLOW_ID:0:7}
    
  
# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  default: 
    jobs:
      - backend-test
      - backend-lint
      - docker-build:
          requires: [backend-test, backend-lint]
      - docker-scan:
          requires: [docker-build]
      - docker-push:
          requires: [docker-scan]