apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotadice
  labels:
    app: gotadice
    ci-hash: latest
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gotadice
  template:
    metadata:
      labels:
        app: gotadice
        ci-hash: latest
    spec:
      containers:
      - name: gotadice
        image: razorbreak/gotadice:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gotadice
  labels:
    app: gotadice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: gotadice